### PR TITLE
Include LICENSE in pypi package

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by joshburnett** [comment]
Thanks, Jan! Good catch.

**Comment by jan-janssen** [comment]
Btw. I created a conda-forge package - https://anaconda.org/conda-forge/scanf - Are you interested to join me in maintaining it? https://github.com/conda-forge/scanf-feedstock

**Comment by joshburnett** [comment]
What all is involved in maintaining a conda package? I've used conda & anaconda a bunch, but have never looked into making my own conda packages.

**Comment by jan-janssen** [comment]
Most of it is automated, it is mainly using the pip package.

**Pull request merged**
